### ISSUE TITLE
Problem negative time after solving

### ISSUE THREAD

**Issue by BaptisteCbl** [BaptisteCbl/CTProblems.jl#2]
@ocots
https://github.com/BaptisteCbl/CTProblems.jl/blob/932e550b96a65c9d16b578d5357b51206833ccd0/src/examples/double_integrator_energy_cc.jl#L77

t1 negative time

**Comment by ocots** [comment]
Just a remark: could you replace `1.0` by `1`, `2.0` by `2`, etc. In every file?

**Comment by ocots** [comment]
Besides: `u[1]` -> `u` when of dimension 1.

**Comment by ocots** [comment]
Be careful, [here](https://github.com/BaptisteCbl/CTProblems.jl/blob/932e550b96a65c9d16b578d5357b51206833ccd0/src/examples/double_integrator_energy_cc.jl#L39):
```julia
    x_arc_1(t,α,β) = [b + γ*t, a + b*t + 0.5*γ*t^2]
```
should be replaced by
```julia
    x_arc_1(t,α,β) = [a + b*t + 0.5*γ*t^2, b + γ*t]
```

**Comment by ocots** [comment]
[Here](https://github.com/BaptisteCbl/CTProblems.jl/blob/932e550b96a65c9d16b578d5357b51206833ccd0/src/examples/double_integrator_energy_cc.jl#L42):
```julia
    d(α,β) = x_arc_1(t1(α,β),α,β)[2] 
```

**Comment by ocots** [comment]
[Here](https://github.com/BaptisteCbl/CTProblems.jl/blob/932e550b96a65c9d16b578d5357b51206833ccd0/src/examples/double_integrator_energy_cc.jl#LL45C51-L45C51):
```julia
    dp(α,β) = d(α,β) - (-0.5*α*t1(α,β)^2 + β*t1(α,β))
```

**Comment by ocots** [comment]
[Here](https://github.com/BaptisteCbl/CTProblems.jl/blob/932e550b96a65c9d16b578d5357b51206833ccd0/src/examples/double_integrator_energy_cc.jl#LL54C30-L54C30):
```julia
    ep(α,β) = e(α,β) - fp(α,β)*t2(α,β) + γ/2*t2(α,β)^2
```

**Comment by ocots** [comment]
[Here](https://github.com/BaptisteCbl/CTProblems.jl/blob/932e550b96a65c9d16b578d5357b51206833ccd0/src/examples/double_integrator_energy_cc.jl#L55):
```julia
    x_arc_3(t,α,β) = [ep(α,β) + fp(α,β)*t - γ/2*t^2, fp(α,β) - γ*t]
```

**Comment by ocots** [comment]
You can close the issue I think.

**Comment by BaptisteCbl** [comment]
It's works, thanks !
