### ISSUE TITLE
Problem on the first run

### ISSUE THREAD

**Issue by BaptisteCbl** [BaptisteCbl/CTProblems.jl#6]
On some examples such as 
```julia
(:integrator, :dim2, :consumption , :control_constraint)
```
the window with the plot of the solutions shows up but all the graphs stay at zero only on the first run.
Running it again solves the problem.   
I have no idea why this behavior occurs.

**Comment by ocots** [comment]
Is it solved?

**Comment by BaptisteCbl** [comment]
The problem is "solved" see #9.
