### ISSUE TITLE
Orbital transfert consumption

### ISSUE THREAD

**Issue by ocots** [BaptisteCbl/CTProblems.jl#7]
File: https://gitlab.irit.fr/toc/maison-de-fermat/-/blob/master/code/transfert-conso-min-100N.jl

Initial guess:
```
[0.0012977929824425805, 
0.00032589568022940377, 
0.0023765992752143887, 
-0.00010621859791207892, 
-0.025235832339334786, 
1.3355190947675691e-14]
```

Figure:

![Capture d’écran 2023-04-06 à 10 26 49](https://user-images.githubusercontent.com/66357348/230321054-ab908a28-d604-4077-a1f3-e5d532b46082.png)

**Comment by ocots** [comment]
The structure seems: +0+0+

**Comment by BaptisteCbl** [comment]
The example seems to work, it has been pushed on the branch orbital_transfer along with the energy and time minimization.
