### ISSUE TITLE
Fix a problem

### ISSUE THREAD

**Issue by ocots** [BaptisteCbl/CTProblems.jl#9]
For the moment, all the problems I have added are visible in this file: https://github.com/control-toolbox/CTProblems.jl/blob/transit/src/CTProblems.jl

The problems that are not tested yet are commented. 

But, I have a problem with "double_integrator_energy_control_constraint.jl". It seems that your solution returns some `NaN`. Can you check?

- The [model/solution file](https://github.com/control-toolbox/CTProblems.jl/blob/transit/src/problems/double_integrator_consumption_control_constraint.jl).
- The [test file](https://github.com/control-toolbox/CTProblems.jl/blob/transit/test/test_double_integrator_energy_control_constraint.jl)

**Comment by ocots** [comment]
I get this:

![Capture d’écran 2023-04-13 à 18 27 20](https://user-images.githubusercontent.com/66357348/231824412-d8e64b6c-0ddc-45b2-863b-50067f0e3dca.png)

**Comment by BaptisteCbl** [comment]
It seems that with the following lines the issue is solved :
```julia
    sol = OptimalControlSolution() #n, m, times, x, p, u)
    sol.state_dimension = n
    sol.control_dimension = m
    sol.times = times
    sol.state = Base.deepcopy(x)
    sol.state_names = [ "x" * ctindices(i) for i ∈ range(1, n)]
    sol.adjoint = Base.deepcopy(p)
    sol.control = Base.deepcopy(u)
    sol.control_names = [ "u" ]
    sol.objective = objective
    sol.iterations = 0
    sol.stopping = :dummy
    sol.message = "structure: B+BaffineB-"
    sol.success = true
    sol.infos[:resolution] = :numerical
```
Adding deepcopy to the state, the control and the adjoint works.
